name: Deploy

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export PATH=$PATH:/home/soumya/.npm-global/bin
             cd /var/www/vms
             git pull origin production
             
            cd backend/
            npm install
            pm2 reload vmsapi

            cd ../frontend
            npm install
            npm run build
            
